const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST"
const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS"
const GET_STUDENT_FAILURE = "GET_STUDENT_FAILURE"

const ADD_STUDENT_REQUEST = "ADD_STUDENT_REQUEST"
const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS"
const ADD_STUDENT_FAILURE = "ADD_STUDENT_FAILURE"

const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST"
const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS"
const DELETE_STUDENT_FAILURE = "DELETE_STUDENT_FAILURE"

const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST"
const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS"
const UPDATE_STUDENT_FAILURE = "UPDATE_STUDENT_FAILURE"

const SEARCH_STUDENT_REQUEST = "SEARCH_STUDENT_REQUEST"
const SEARCH_STUDENT_SUCCESS = "SEARCH_STUDENT_SUCCESS"
const SEARCH_STUDENT_FAILURE = "SEARCH_STUDENT_FAILURE"



export {
    GET_STUDENT_FAILURE,
    GET_STUDENT_REQUEST,
    GET_STUDENT_SUCCESS,
    ADD_STUDENT_FAILURE,
    ADD_STUDENT_REQUEST,
    ADD_STUDENT_SUCCESS,
    DELETE_STUDENT_FAILURE,
    DELETE_STUDENT_REQUEST,
    DELETE_STUDENT_SUCCESS,
    UPDATE_STUDENT_FAILURE,
    UPDATE_STUDENT_REQUEST,
    UPDATE_STUDENT_SUCCESS,
    SEARCH_STUDENT_FAILURE,
    SEARCH_STUDENT_REQUEST,
    SEARCH_STUDENT_SUCCESS
}